name: ⚠️ Delete ACM Certificate

on:
  workflow_dispatch:
  workflow_call:

jobs:
  delete:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        uses: aws-actions/setup-sam@v2

      - name: Delete ACM Certificate stack
        run: |
          sam delete \
            --stack-name firefly-acm-certificate \
            --region ${{ secrets.AWS_REGION }} \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }} \
            --no-prompts