name: ðŸš€ Deploy DynamoDB Firmware Table

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        uses: aws-actions/setup-sam@v2

      - name: Build DynamoDB firmware table
        run: sam build --template-file templates/dynamodb-firmware.yaml

      - name: Deploy DynamoDB table
        run: |
          sam deploy \
            --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.CLOUD_FORMATION_EXECUTION_ROLE_NAME }} \
            --template-file templates/dynamodb-firmware.yaml \
            --stack-name firefly-dynamodb-firmware \
            --region ${{ secrets.AWS_REGION }} \
            --parameter-overrides \
              DynamoDbFirmwareTableName=${{ vars.DYNAMODB_FIRMWARE_TABLE_NAME }} \
            --no-confirm-changeset \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }}