name: ðŸš€ Deploy S3 Firmware
on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-s3-firmware:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        uses: aws-actions/setup-sam@v2

      - name: Look up Lambda ARN for func-s3-firmware-uploaded
        id: lookup_uploaded
        run: |
          UPLOAD_ARN=$(aws lambda get-function \
            --function-name firefly-func-s3-firmware-uploaded \
            --query 'Configuration.FunctionArn' \
            --output text)

          echo "upload_arn=$UPLOAD_ARN" >> $GITHUB_OUTPUT

      - name: Look up Lambda ARN for func-s3-firmware-deleted
        id: lookup_deleted
        run: |
          DELETE_ARN=$(aws lambda get-function \
            --function-name firefly-func-s3-firmware-deleted \
            --query 'Configuration.FunctionArn' \
            --output text)

          echo "delete_arn=$DELETE_ARN" >> $GITHUB_OUTPUT

      - name: Build s3-firmware
        run: sam build --template-file templates/s3-firmware.yaml

      - name: Deploy s3-firmware
        run: |
          sam deploy \
            --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.CLOUD_FORMATION_EXECUTION_ROLE_NAME }} \
            --template-file templates/s3-firmware.yaml \
            --stack-name firefly-s3-firmware \
            --region ${{ secrets.AWS_REGION }} \
            --parameter-overrides \
              BucketName=${{ secrets.S3_FIRMWARE_BUCKET_NAME }} \
              FirmwareUploadLambdaArn=${{ steps.lookup_uploaded.outputs.upload_arn }} \
              FirmwareDeleteLambdaArn=${{ steps.lookup_deleted.outputs.delete_arn }} \
            --no-confirm-changeset \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }}